### PR TITLE
Fix #5: Return Result, rather than panicking

### LINKED ISSUE #5: Return Result, rather than panicking

### PR DESCRIPTION
**Pull request by khernyo**

### CODE REVIEW

**Comment by nrc** [comment]
Awesome, thank you!

**Comment by jethrogb** [comment]
Why do some functions that never fail now return `Result`?

Also, I must say I'm not a big fan of string error messages.

**Comment by khernyo** [comment]
I guess that's a mistake, but I have to check. Could you point out one of those functions?

I agree, string errors are not the best. That's what I had time for, though.

**Comment by jethrogb** [comment]
At least `get_type` and `get_tag` and perhaps others. I expect only function that reference other parts of the ELF structure (like `get_name` etc.) to potentially fail.

**Comment by jethrogb** [comment]
Oh nevermind, upon closer look, I see now that those do panic if the value in the ELF is not specified by the standard.

**Pull request merged**
